
A89TH_BN_GRP = { "A89BN_MBT_TEMP1", "A89BN_MBT_TEMP2", "A89BN_MBT_TEMP3" } 


-- ME ZONE NAME SSADAZONE


-- SS AAA
do

rng = math.random( 1, 1 )
  if rng == 1 then

A89TH_BN_ZONE_POLY1 = ZONE_POLYGON:New( "A89TH_BN_ZONE_POLY#001", GROUP:FindByName( "A89TH_BN_ZONE_POLY#001"))
A89TH_BN_ZONE_POLY2 = ZONE_POLYGON:New( "A89TH_BN_ZONE_POLY#002", GROUP:FindByName( "A89TH_BN_ZONE_POLY#002"))
A89TH_BN_ZONE_POLY3 = ZONE_POLYGON:New( "A89TH_BN_ZONE_POLY#003", GROUP:FindByName( "A89TH_BN_ZONE_POLY#003"))
A89TH_BN_ZONE_POLY4 = ZONE_POLYGON:New( "A89TH_BN_ZONE_POLY#004", GROUP:FindByName( "A89TH_BN_ZONE_POLY#004"))
A89TH_BN_ZONE_POLY5 = ZONE_POLYGON:New( "A89TH_BN_ZONE_POLY#005", GROUP:FindByName( "A89TH_BN_ZONE_POLY#005"))
A89TH_BN_ZONE_POLY6 = ZONE_POLYGON:New( "A89TH_BN_ZONE_POLY#006", GROUP:FindByName( "A89TH_BN_ZONE_POLY#006"))
A89TH_BN_ZONE_POLY7 = ZONE_POLYGON:New( "A89TH_BN_ZONE_POLY#007", GROUP:FindByName( "A89TH_BN_ZONE_POLY#007"))
A89TH_BN_ZONE_POLY8 = ZONE_POLYGON:New( "A89TH_BN_ZONE_POLY#008", GROUP:FindByName( "A89TH_BN_ZONE_POLY#008"))


A89TH_BN_ZoneTable = {A89TH_BN_ZONE_POLY1,
              A89TH_BN_ZONE_POLY2,
              A89TH_BN_ZONE_POLY3,
              A89TH_BN_ZONE_POLY4,
              A89TH_BN_ZONE_POLY5,
              A89TH_BN_ZONE_POLY6,
              A89TH_BN_ZONE_POLY7,
              A89TH_BN_ZONE_POLY8}

    A89TH_BN = SPAWN:NewWithAlias( "A89BN_MBT_TEMP1" )
    :InitLimit( 60, 5 )
    :InitRandomizeZones( A89TH_BN_ZoneTable )
    :InitRandomizeTemplate( A89TH_BN_GRP )
    :InitAIOff()
    :SpawnScheduled( 5, .5 )
    
 table.remove(A89TH_BN_ZoneTable)

  end

end



A89TH_BN_GRP_CITY = { "A89BN_MBT_TEMP11" } 


-- ME ZONE NAME SSADAZONE


-- SS AAA
do

rng = math.random( 1, 1 )
  if rng == 1 then

A89THCITY_BN_ZONE_POLY1 = ZONE_POLYGON:New( "A89THCITY_BN_ZONE_POLY#001", GROUP:FindByName( "A89THCITY_BN_ZONE_POLY#001"))
A89THCITY_BN_ZONE_POLY2 = ZONE_POLYGON:New( "A89THCITY_BN_ZONE_POLY#002", GROUP:FindByName( "A89THCITY_BN_ZONE_POLY#002"))
A89THCITY_BN_ZONE_POLY3 = ZONE_POLYGON:New( "A89THCITY_BN_ZONE_POLY#003", GROUP:FindByName( "A89THCITY_BN_ZONE_POLY#003"))
A89THCITY_BN_ZONE_POLY4 = ZONE_POLYGON:New( "A89THCITY_BN_ZONE_POLY#004", GROUP:FindByName( "A89THCITY_BN_ZONE_POLY#004"))
A89THCITY_BN_ZONE_POLY5 = ZONE_POLYGON:New( "A89THCITY_BN_ZONE_POLY#005", GROUP:FindByName( "A89THCITY_BN_ZONE_POLY#005"))
A89THCITY_BN_ZONE_POLY6 = ZONE_POLYGON:New( "A89THCITY_BN_ZONE_POLY#006", GROUP:FindByName( "A89THCITY_BN_ZONE_POLY#006"))
A89THCITY_BN_ZONE_POLY7 = ZONE_POLYGON:New( "A89THCITY_BN_ZONE_POLY#007", GROUP:FindByName( "A89THCITY_BN_ZONE_POLY#007"))
A89THCITY_BN_ZONE_POLY8 = ZONE_POLYGON:New( "A89THCITY_BN_ZONE_POLY#008", GROUP:FindByName( "A89THCITY_BN_ZONE_POLY#008"))


A89THCITY_BN_ZoneTable = {A89THCITY_BN_ZONE_POLY1,
              A89THCITY_BN_ZONE_POLY2,
              A89THCITY_BN_ZONE_POLY3,
              A89THCITY_BN_ZONE_POLY4,
              A89THCITY_BN_ZONE_POLY5,
              A89THCITY_BN_ZONE_POLY6,
              A89THCITY_BN_ZONE_POLY7,
              A89THCITY_BN_ZONE_POLY8}

    A89TH_BN_CITY = SPAWN:NewWithAlias( "A89BN_MBT_TEMP11" )
    :InitLimit( 60, 5 )
    :InitRandomizeZones( A89THCITY_BN_ZoneTable )
    :InitRandomizeTemplate( A89TH_BN_GRP_CITY )
    :InitAIOff()
    :SpawnScheduled( 5, .5 )
    
 table.remove(A89THCITY_BN_ZoneTable)

  end

end
